export enum ShoppingStoreActions {
  ADD_INGREDIENT = '[Shopping List] -> ADD INGREDIENT',
  ADD_INGREDIENTS = '[Shopping List] -> ADD INGREDIENTS',
  DELETE_INGREDIENT = '[Shopping List] -> DELETE INGREDIENT',
  DELETE_INGREDIENTS = '[Shopping List] -> DELETE INGREDIENTS',
  UPDATE_INGREDIENT = '[Shopping List] -> UPDATE INGREDIENT',
  START_INGREDIENT_UPDATE = '[Shopping List] -> START INGREDIENT UPDATE',
  STOP_INGREDIENT_UPDATE = '[Shopping List] -> STOP INGREDIENT UPDATE'
}
